#!/usr/bin/env python3
"""
Merge all batch files into the final seed_course_content.py,
then run seed and rebuild frontend.
"""
import ast, sys, os

os.chdir(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

# Collect valid batches
batch_files = []
for fname in sorted(os.listdir('.')):
    if fname.startswith('seed_course_content_batch') and fname.endswith('.py'):
        # Try to parse
        try:
            with open(fname) as f:
                compile(f.read(), fname, 'exec')
            batch_files.append(fname)
        except SyntaxError as e:
            print(f"⚠️  Skipping {fname}: syntax error at line {e.lineno}")

print(f"Valid batches: {batch_files}")

# Extract COURSE_CONTENT from each
all_courses = {}
for fname in batch_files:
    with open(fname) as f:
        tree = ast.parse(f.read())
    for node in ast.walk(tree):
        if isinstance(node, ast.Assign) and hasattr(node.targets[0], 'id') and node.targets[0].id == 'COURSE_CONTENT':
            for key, value in zip(node.value.keys, node.value.values):
                k = key.value
                v = ast.literal_eval(value)
                all_courses[k] = v

print(f"Merged courses: {sorted(all_courses.keys())}")

# Check we have all 24 (courses 7-30)
expected = set(range(7, 31))
missing = expected - set(all_courses.keys())
if missing:
    print(f"❌ Missing courses: {sorted(missing)}")
    sys.exit(1)

print(f"✅ All 24 courses (7-30) present, {sum(len(v) for v in all_courses.values())} total chapters")

# Now merge with existing seed_course_content.py (courses 1-6)
# Read existing file
with open('seed_course_content.py') as f:
    existing_content = f.read()

# The existing file has COURSE_CONTENT = { 1: [...], 2: [...], ..., 10: [...] }
# We need to extract courses 1-10 from it
existing_tree = ast.parse(existing_content)
existing_courses = {}
for node in ast.walk(existing_tree):
    if isinstance(node, ast.Assign) and hasattr(node.targets[0], 'id') and node.targets[0].id == 'COURSE_CONTENT':
        for key_node, value_node in zip(node.value.keys, node.value.values):
            try:
                k = ast.literal_eval(key_node)
                v = ast.literal_eval(value_node)
                existing_courses[k] = v
            except:
                pass

# Courses 1-6 we keep from existing, courses 11-16 from batch2, etc.
# Actually the existing file had courses 1-10, batch1 is 7-11, batch2 is 12-16, etc.
# We'll prefer batch content for courses 7+ and keep existing for 1-6
final_courses = {}
for k in range(1, 7):
    if k in existing_courses:
        final_courses[k] = existing_courses[k]
for k in range(7, 31):
    if k in all_courses:
        final_courses[k] = all_courses[k]

print(f"Final courses: {sorted(final_courses.keys())}")
print(f"Total chapters: {sum(len(v) for v in final_courses.values())}")

# Generate the Python file
header = '''# -*- coding: utf-8 -*-
"""
Seed course chapter content for all 30 courses.
Auto-generated by merge_course_content.py
"""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from sqlalchemy import create_engine, select
from sqlalchemy.orm import Session
from config import SYNC_DATABASE_URL
from models import Base, Course

engine = create_engine(SYNC_DATABASE_URL, echo=False)
Base.metadata.create_all(bind=engine)

COURSE_CONTENT = {
'''

footer = '''}


def seed_course_content():
    """Seed all 30 courses into the database."""
    with Session(engine) as session:
        for course_id, chapters in COURSE_CONTENT.items():
            course = session.get(Course, course_id)
            if course:
                course.content = chapters
                print(f"  Updated course {course_id}: {course.title} ({len(chapters)} chapters)")
        session.commit()
    print(f"\\n✅ Seeded {len(COURSE_CONTENT)} courses")


if __name__ == "__main__":
    seed_course_content()
'''

with open('seed_course_content.py', 'w', encoding='utf-8') as f:
    f.write(header)
    for k in sorted(final_courses.keys()):
        f.write(f"    {k}: {repr(final_courses[k])},\n")
    f.write(footer)

# Validate
with open('seed_course_content.py') as f:
    try:
        compile(f.read(), 'seed_course_content.py', 'exec')
        print("✅ Final file passes syntax check")
    except SyntaxError as e:
        print(f"❌ Syntax error in final file: {e}")

print(f"\nFinal file size: {os.path.getsize('seed_course_content.py')} bytes")
